# SwiftLint configuration for AudioType

included:
  - AudioType
  - WhisperWrapper

excluded:
  - whisper.cpp
  - .build
  - AudioType.app

# Rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - fallthrough
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Configuration
identifier_name:
  min_length: 1
  max_length: 50
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k

type_name:
  min_length: 2
  max_length: 50

nesting:
  type_level: 3
  function_level: 3

cyclomatic_complexity:
  warning: 15
  error: 25

large_tuple:
  warning: 4
  error: 5

reporter: "xcode"
